// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Coordinates struct {
	Lat  float64 `json:"lat"`
	Long float64 `json:"long"`
}

type InputCoordinates struct {
	Lat  float64 `json:"lat"`
	Long float64 `json:"long"`
}

type InputParams struct {
	Offset *int `json:"offset,omitempty"`
	Limit  *int `json:"limit,omitempty"`
}

type LoginResponse struct {
	Status      string  `json:"status"`
	Error       *string `json:"error,omitempty"`
	AccessToken string  `json:"AccessToken"`
}

type Mutation struct {
}

type Query struct {
}

type Response struct {
	Status string  `json:"status"`
	Error  *string `json:"error,omitempty"`
}

type Sighting struct {
	Timestamp   *string      `json:"timestamp,omitempty"`
	Coordinates *Coordinates `json:"coordinates,omitempty"`
}

type Tiger struct {
	ID                  string       `json:"_id"`
	Name                *string      `json:"name,omitempty"`
	Dob                 *string      `json:"dob,omitempty"`
	LastSeenTimeStamp   string       `json:"lastSeenTimeStamp"`
	LastSeenCoordinates *Coordinates `json:"lastSeenCoordinates"`
	ImageURL            *string      `json:"imageURL,omitempty"`
	ReporterUserName    string       `json:"reporterUserName"`
}

type TigerSightings struct {
	Name      *string     `json:"name,omitempty"`
	Sightings []*Sighting `json:"sightings,omitempty"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateTigerInput struct {
	Name                string            `json:"name"`
	Dob                 string            `json:"dob"`
	LastSeenTimeStamp   string            `json:"lastSeenTimeStamp"`
	ImageURL            *string           `json:"imageURL,omitempty"`
	LastSeenCoordinates *InputCoordinates `json:"lastSeenCoordinates"`
	ReporterUserName    string            `json:"reporterUserName"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginUserInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SightingOfTigerInput struct {
	LastSeenTimeStamp   string            `json:"lastSeenTimeStamp"`
	LastSeenCoordinates *InputCoordinates `json:"lastSeenCoordinates"`
	ImageURL            string            `json:"imageURL"`
	ReporterUserName    string            `json:"reporterUserName"`
}
